/**
 * Deterministic rendering of the maintained reviewer-report comment.
 *
 * Pure presentation over validated inputs: the publisher supplies the parsed
 * payload/context, the published commit (if any), the blob enumeration of the
 * linked tree, and pre-validated server/run URLs, then posts the returned
 * body verbatim. Agent-authored prose crosses the text.ts rendering boundaries
 * here, and evidenceLink stays the only agent-supplied URL that can render.
 */

import type { RepairPayload } from "./repair-payload.ts";
import { REPORT_MARKER, generatorName, renderReportState } from "./report-state.ts";
import type { RunContext } from "./run-context.ts";
import { cleanReportText, evidenceLink, linkifyRepoPaths, repoFileUrl } from "./text.ts";

const MAX_COMMENT_CHARS = 60_000;
const MAX_REPORT_LINKS = 500;

export interface ReportLinkInputs {
  /** SHA of the published repair commit, or null for a no-repair or deferred review. */
  commitSha: string | null;
  /** Blob paths of the tree file links point into: the repair commit, or the snapshotted head. */
  blobPaths: ReadonlySet<string>;
  /** Validated https origin every built URL starts from. */
  server: string;
  /** Validated Actions-run URL for the footer, or null to render it unlinked. */
  runUrl: string | null;
}

function bullets(
  items: readonly string[],
  empty: string,
  render: (value: string) => string,
): string {
  return items.length > 0 ? items.map((item) => `- ${render(item)}`).join("\n") : `- ${empty}`;
}

/** Render the full marker comment, capped in size and link count. */
export function renderReportBody(
  payload: RepairPayload,
  context: RunContext,
  links: ReportLinkInputs,
): string {
  const agent = payload.agent;
  const { commitSha, blobPaths, server, runUrl } = links;
  const linkSha = commitSha ?? context.pullRequest.headSha;
  let linkCount = 0;
  const fileUrl = (path: string): string | null => {
    if (linkCount >= MAX_REPORT_LINKS || !blobPaths.has(path)) return null;
    const url = repoFileUrl(server, payload.repository, linkSha, path);
    if (url !== null) linkCount += 1;
    return url;
  };
  const prose = (value: string, max?: number): string =>
    linkifyRepoPaths(cleanReportText(value, max), fileUrl);
  const upstream =
    agent.upstream_changes.length > 0
      ? agent.upstream_changes
          .map(
            (item) =>
              `- **${cleanReportText(item.dependency, 200)}:** ${prose(item.change)} ` +
              `_${prose(item.relevance)}_${evidenceLink(item.evidence_url)}`,
          )
          .join("\n")
      : "- No repository-relevant upstream change stood out from the available evidence.";
  const verification =
    agent.verification.length > 0
      ? agent.verification
          .map(
            (item) =>
              `- \`${cleanReportText(item.command, 500).replaceAll("`", "\\`")}\` — **${item.outcome}**: ` +
              prose(item.evidence),
          )
          .join("\n")
      : "- No local verification result was available.";
  const heading =
    agent.verdict === "defer"
      ? "Depvisor deferred this update"
      : commitSha
        ? "Depvisor published a repair"
        : "Depvisor reviewed this update";
  const runLink = runUrl === null ? "" : ` ([workflow run](${runUrl}))`;
  // Record the reviewed head only for a no-repair review: a published repair
  // moves the branch head, and the next CI pass must review that new head.
  const stateLine =
    commitSha === null && agent.verdict !== "defer"
      ? renderReportState({
          headSha: context.pullRequest.headSha,
          conclusion: context.trigger.conclusion,
          generator: generatorName(),
        })
      : null;
  const body = `${REPORT_MARKER}${stateLine === null ? "" : `\n${stateLine}`}
## ${heading}

${prose(agent.summary)}

### Relevant upstream changes

${upstream}

### Repair

${bullets(agent.changes_made, commitSha ? "The repair commit contains the working-tree changes listed above." : "No code repair was needed.", prose)}
${commitSha ? `\nRepair commit: \`${commitSha}\`` : ""}

### Verification evidence

${verification}

### Residual risks

${bullets(agent.risks, "No additional repository-specific risk was identified.", prose)}
${agent.verdict === "defer" ? `\n**Why depvisor deferred:** ${prose(agent.defer_reason || "No safe bounded repair was found.")}` : ""}

Initial CI: **${cleanReportText(context.trigger.conclusion, 100)}**${context.trigger.url ? ` — ${cleanReportText(context.trigger.workflowName || "workflow run", 200)}${evidenceLink(context.trigger.url)}` : ""}.

_Generated by ${generatorName()}${runLink}. Review before merging._`;
  return body.slice(0, MAX_COMMENT_CHARS);
}
